### ISSUE TITLE
10-Q filings Facts to pandas dataframe

### ISSUE THREAD

**Issue by vpanchal-code** [dgunning/edgartools#10]
First of all, This is really amazing! I am enjoying using it and makes it much more easier to find filings than the edgar sec website. 

Is there a way to convert the latest 10-Q filing data to a pandas dataframe?

```python
from edgar import *
set_identity("first last first.last@gmail.com")
company = Company(909832)
last10q = company.get_filings(form="10-Q").latest()
last10q.xbrl()
```

**Comment by dgunning** [comment]
`

xbrl = last10q.xbrl()
facts = xbrl.facts
df = facts.data
`
