### ISSUE TITLE
Question: get_filings for specific CIKs

### ISSUE THREAD

**Issue by grtax1gh** [dgunning/edgartools#102]
Hello,

I want to download 10-K filings for specific CIKs only. However, when I used `get_filings` function, I could not figure out how to include a patemeter that can "filter" CIKs.
Would you kindly advise how to do so?
I'm new to Python and tried to look at the closed questions but it seems no one has raised this point yet.
I don't want to download all the filings then filter the CIKs I need. I had tried it, but ended up with nothing because of connection/timing issue (as mentioned in [Taking a long time #75](https://github.com/dgunning/edgartools/issues/75)).

```
from edgar import *
import pandas as pd

set_identity("name name name.name1@mail.com")

filings = get_filings(year= [2024], form = "10-K", amendments= False,
                      filing_date="2024-03-01")
```

**Comment by dgunning** [comment]
Try

```python

filings.filter(cik=[<list of ciks>])
```

This is mentioned here https://github.com/dgunning/edgartools/wiki/FindingThings#filtering-filings but I will add it to the main documentation.
