### ISSUE TITLE
Interest Expenses and EBITDA

### ISSUE THREAD

**Issue by PeterLuger** [dgunning/edgartools#12]
Hello,
is there a way to retrieve the information on interest expenses (needed to calculate EBITDA for a company)?
Or is a synonym used?

Regards,
Peter

**Comment by dgunning** [comment]
Try

# Get a filing using any means. One way
orcl = Company("ORCL")
filing = orcl.get_filings(form="10-K").latest(1)

# Get the filing xbrl then query the GAAP
xbrl = filing.xbrl()
xbrl.gaap.query("fact=='InterestExpense'")

# xbrl.gaap is a pandas dataframe

I am implementing an easier way to do this for InterestExpense in a minor version later this week. Currently you have to know that the fact is called InterestExpense

**Comment by dgunning** [comment]
Added interest expense in 2.1.1

Now possible from the company financials (the latest 10-K)
` Company("TSLA").financials.income_statement.interest_expense`

Or from the latest 10-Q
`Company("TSLA").get_filings(form='10-Q').latest(1).obj().income_statement.interest_expense

All the data is available in the gaap

`xbrl.gaap.query("fact=='InterestExpense'")

**Comment by dgunning** [comment]
Closed
