### ISSUE TITLE
Amendments Filtering not Working

### ISSUE THREAD

**Issue by NewbingandBard** [dgunning/edgartools#121]
Hello! Thank the team for this awesome project.
I'm working to get the 10-K-like filings (exclude amendments). But some amendments were not filtered correctly (using amendments=False).
```
company_filings = get_filings(year=year, form=["10-K", "20-F", "40-F"])
company_filings = company_filings.filter(ticker=ticker, amendments=False)
print(company_filings) #Debug use
```
For instance, when dealing with the 2022 NEM (ticker) filing:
<img width="1372" alt="image" src="https://github.com/user-attachments/assets/082b3cc3-93c2-483e-949c-c12d3ebbf7a0">
I'm wondering if it is a bug, or I misoperated something? Thanks in advance!

**Comment by dgunning** [comment]
Oh .. you have found a bug. `filter(amendments=False)` does not work but `get_filings(amendment=False)` does

Try

```python
company_filings = get_filings(year=2022, form=["10-K", "20-F", "40-F"], amendments=False).filter(ticker="NEM")
```
I will do a fix.

Thanks

**Comment by dgunning** [comment]
Fixed
