### ISSUE TITLE
Error fetching or processing filings: Failed to fetch filings index: 429

### ISSUE THREAD

**Issue by david08-08** [dgunning/edgartools#124]
Is this unusual? I have never had this happen before. I am getting flagged for too many requests. Please advise on what to do or how to handle this.

**Comment by dgunning** [comment]
This condition is rare but it can happen depending on how the code is written. How was your code being run - in a batch script or by a user?

**Comment by david08-08** [comment]
I figured this out

**Comment by dgunning** [comment]
Sorry for not helping before you figured it out, but glad you did, I've been busy, but catching up now
