### ISSUE TITLE
Search specific data from the SEC Files

### ISSUE THREAD

**Issue by MuslemRahimi** [dgunning/edgartools#126]
Hey everyone,

I just wanted to know if it is possible to get specific data such as Data Center Revenue from Nvidia for each quarter which they report for the last 10 years.

Is that possible with the current library here?

Cheers

**Comment by MuslemRahimi** [comment]
Ok i have now
`
from edgar import *

# Tell the SEC who you are
set_identity("Michael Mccallum mike.mccalum@indigo.com")


filings = Company("NVDA").get_filings(form="10-Q").latest(10)
print(filings)
output = filings[0].search("Revenue by Geography")

print(output[18])

`
where the output is 
![image](https://github.com/user-attachments/assets/68961439-9568-4c0c-a8b2-32687a44ee5b)

How can I convert the data which has docsection type into a pandas dataframe?

**Comment by dgunning** [comment]
Hey, I'm going to say no - not yet, but I'm actively working on a related issue around trying to get the breakdowns to display correctly. I will give an update on this based on my progress over the next few days

**Comment by MuslemRahimi** [comment]
Any updates yet?

**Comment by dgunning** [comment]
Yes,

```python
c = Company("NVDA")
xb = c.get_filings(form="10-Q").latest(1).xbrl()
```
Look for the statement number
<img width="556" alt="Statements" src="https://github.com/user-attachments/assets/d53b202f-3219-4b33-9372-57998b1d2172">


```python
xb.statements[70]
```
<img width="676" alt="ByRegion" src="https://github.com/user-attachments/assets/d79632bf-94c5-40b9-b18d-a5b32c574492">

**Comment by dgunning** [comment]
Yes. Use

```python
 xb.statements[70].get_dataframe()
```

**Comment by dgunning** [comment]
Closed as answered
