### ISSUE TITLE
XBRL- NOW QUARTERLY FILINGS-Possible Bug? 

### ISSUE THREAD

**Issue by david08-08** [dgunning/edgartools#135]
When using the XBRL library for quarterly filings specific to ticker symbol NOW there are statements missing. I attached the excel file that contains the most recent reported quarter which was last week. 

[NOW_XBRL_Financials_2024.xlsx](https://github.com/user-attachments/files/17531649/NOW_XBRL_Financials_2024.xlsx)

Here is the link for NOW's most recent quarterly financial statement: 
https://www.sec.gov/ix?doc=/Archives/edgar/data/1373715/000137371524000272/now-20240630.htm

Is this a bug? Please advise.

**Comment by dgunning** [comment]
Hi David, 

The latest filing for NOW is for June 30th. Do you mean the filing is not yet available OR some stamens within the financials are not available.?

<img width="719" alt="NOW-financials" src="https://github.com/user-attachments/assets/4820d95e-847b-4304-a59f-09f649b0261a">

**Comment by david08-08** [comment]
Hi Dwight, 

Thank you for the response. That's correct the June 30th report. The filing is available but there are statements within the financials that are not being exported to excel.  The only ones that are showing up are the Condensed/Consolidated Balance Sheet and Condensed/Consolidated Statement of Cash Flows.

**Comment by david08-08** [comment]
Is there anyone that can help me here or provide code to fix this? I would greatly appreciate it. @dgunning

**Comment by dgunning** [comment]
Fixed
