### ISSUE TITLE
XBRL- TER QUARTERLY FILING (same issue as NOW) & when pulling through TENQ the Cash Flow statement is not exporting to excel for TER and NOW.  Possible Bug? 

### ISSUE THREAD

**Issue by david08-08** [dgunning/edgartools#139]
Hi Dwight, 

I just noticed the same thing as well with ticker symbol TER. Not all the statements are being exported to excel when using the XBRL library for the most recent quarterly statement which was issued this past week. I listed the statements below. In addition when pulling the quarterly filing using the TENQ library the cash flow statement is not exporting to excel. 

Please advise. Thank you. 

Screenshot when pulling through TENQ:

<img width="1514" alt="Screenshot 2024-10-27 at 2 15 17 PM" src="https://github.com/user-attachments/assets/63650eeb-f960-446a-937f-89c4a08fbfe4">

XBRL statements missing from most recent quarterly filing:

  | Condensed Consolidated Statements of Operations for the Three and Six Months ended June 30, 2024 and July 2, 2023 | 2

  | Condensed Consolidated Statements of Comprehensive Income for the Three and Six Months ended June 30, 2024, and July 2, 2023

**Comment by david08-08** [comment]
Here is the code I am using 

import pandas as pd
from rich import print
from edgar import Company, set_identity
from edgar.company_reports import TenK, TenQ, TwentyF, EightK
from edgar.htmltools import ChunkedDocument

set_identity("david@gmail.com")


pd.options.display.max_colwidth = 40

# Pull financial data for NOW Stock
tenq = Company("NOW").get_filings(form="10-Q")[0].obj()
financials = tenq.financials

# Extract financial statements as DataFrames using the get_dataframe() method
balance_sheet_df = financials.get_balance_sheet().get_dataframe()
cash_flow_df = financials.get_cash_flow_statement().get_dataframe()
income_statement_df = financials.get_income_statement().get_dataframe()

# Inspect the structure of the DataFrames to ensure labels and numbers are included
print(balance_sheet_df.head())  # For checking the first few rows
print(cash_flow_df.head())
print(income_statement_df.head())

# Set file path to your Documents folder
output_file = "/Users/david/Documents/NOW_10Q_Financials_with_labels.xlsx"

# Write data to Excel with separate sheets
with pd.ExcelWriter(output_file, engine='xlsxwriter') as writer:
    balance_sheet_df.to_excel(writer, sheet_name='Balance Sheet', index=True)  # Include index if labels are part of it
    cash_flow_df.to_excel(writer, sheet_name='Cash Flow Statement', index=True)
    income_statement_df.to_excel(writer, sheet_name='Income Statement', index=True)

print(f"NOW 10-Q Financials with labels have been saved to {output_file}"

If there is another code I should be using or if you can provide an enhancement  so I can get this fixed I would greatly appreciate it. @pierotofy @dgunning

**Comment by dgunning** [comment]
I see the issue. Investigating

**Comment by david08-08** [comment]
Hi Dwight, thank you. Please let me know as soon as you can. I appreciate your help. @dgunning

**Comment by dgunning** [comment]
**TER**
```python
>>> xb = Company('TER').get_filings(form='10-Q').latest(1).xbrl()
>>> xb.statements[3].get_dataframe()
```
<img width="627" alt="TER" src="https://github.com/user-attachments/assets/65c8200a-817f-4420-b737-ac6c20d13d94">

Works for NOW and TER
NOW

<img width="633" alt="NOW" src="https://github.com/user-attachments/assets/541adc78-6b04-4ed5-ade3-a6b023fb1042">
