### ISSUE TITLE
get_bool function parses String field value 'true' as boolean False

### ISSUE THREAD

**Issue by Iskaldr** [dgunning/edgartools#14]
The current implementation of the edgar.core.get_bool function returns `False`, if the string field value is String `'true'`, therefore returning wrong reporting_relationship for some filings, e.g. 
[this filing](https://www.sec.gov/Archives/edgar/data/1868662/000141588923014419/xslF345X05/form4-10182023_111040.xml) will be parsed to `is_officer = False`, but should be `is_officer = True`

**Comment by dgunning** [comment]
Thanks Christian, I am taking a look

**Comment by dgunning** [comment]
Fixed in 2..4.1.

**Comment by dgunning** [comment]
Fixed
