### ISSUE TITLE
Update from issue #139. Quarterly Cash Flow Statements I tried using many Tickers 

### ISSUE THREAD

**Issue by david08-08** [dgunning/edgartools#140]
I have pulled many tickers using the Tenq library this morning and the same thing keeps happening. 

When I use the first two codes below to pull the statements the Balance Sheet and Income Statements are fine but the Cash Flow Statement is only importing the labels but not the numbers. But when I use the last code to pull the financial statements everything comes in fine. It looks like there is something wrong. 

# Pull financial data for PANW Stock
tenq = Company("PANW").get_filings(form="10-Q")[0].obj()
financials = tenq.financials

# Pull financial data for PANW Stock
tenq = Company("PANW").get_filings(form="10-Q")[1].obj()
financials = tenq.financials

# Pull financial data for PANW Stock
tenq = Company("PANW").get_filings(form="10-Q")[2].obj()
financials = tenq.financials

**Comment by dgunning** [comment]
Hi David,

I found the issue, it has to do with the logic for selecting '3 month' or '6 month' data, there was a bug. Doing the fix now.

**Comment by david08-08** [comment]
Hi Dwight, 

Awesome, thank you for your time and help. I appreciate it. Will you let me know when it is fixed? Thank you again. @dgunning 

David

**Comment by david08-08** [comment]
Good afternoon, Dwight. Just curious do you have an ETA on the fix? Not a huge deal just wondering what the ETA is. Thank you again. @dgunning 

David

**Comment by dgunning** [comment]
Currently working on it, maybe Thursday

**Comment by david08-08** [comment]
Hi Dwight, Good afternoon. Just checking-in. Is there any news on this fix? Thank you 

David 
@dgunning

**Comment by dgunning** [comment]
Release 3.0.4 with a fix.

**Comment by dgunning** [comment]
Works now for PANW
<img width="620" alt="PANW" src="https://github.com/user-attachments/assets/c38139fa-691c-4789-9051-7f8f3a7c70c8">
