### ISSUE TITLE
XBRL Quarterly Statements Still Not Working---

### ISSUE THREAD

**Issue by david08-08** [dgunning/edgartools#142]
Dwight, Thank you for the update. I am able to receive cash flow statements now when pulling via TENQ. 

Can you please confirm if we are able to get the XBRL financial statements with the current library? I am still not receiving all the financial statements when pulling XBRL Quarterly. Please confirm if we are able to. @dgunning 

Thank you, 
David

**Comment by dgunning** [comment]
Fixed
