### ISSUE TITLE
XBRL QUARTERLY STATEMENTS STILL NOT WORKING- NOW 

### ISSUE THREAD

**Issue by david08-08** [dgunning/edgartools#143]
Hi Dwight, 

Thank you for your time and help. 

I saw the code you provided earlier today and ran it a few times. The output is still not correct. I am not getting all the quarterly XBRL statements still for NOW. 

Is the issue because of the 31 character limit when exporting to excel? Because some statements are exporting but others are not. Do you think this is the problem? 

Please let me know I am working on a project that I am trying to get done using your library but I keep running into issues. I appreciate your help and time. 

David 
@dgunning

**Comment by dgunning** [comment]
Fixed
