### ISSUE TITLE
Question about xbrl

### ISSUE THREAD

**Issue by onthegit** [dgunning/edgartools#145]
Hello, 
thanks for the project. When parsing XBRL, how to get the description of xbrl elements (e.g us-gaap:EMEAMember) and others?

https://xbrlsite.azurewebsites.net/2019/Prototype/references/us-gaap/Element-4838.html

explains that this is
Regions of Europe, Middle East and Africa.

how do they retrieve this description? It is nowhere to be found in the filing.

Thanks.

**Comment by dgunning** [comment]
I think that comes from the xml linkbase schema. It won't be in the filing or XBRL parsed by edgartools

**Comment by onthegit** [comment]
where can i find this scheme? is there some xml or json. i searched everywhere and could not find these except on the link above.

**Comment by onthegit** [comment]
Thank you for your reply. When parsing the xbrl for balance sheet or other statements,  how do you know which item belongs where? e.g Cash under current assets?
