### ISSUE TITLE
XBRL RECENT QUARTERLY STATEMENTS- META, HD, VKTX- CONDENSEDCONSOLIDATEDSTATEMENTSOFSTOCKHOLDERSEQUITY- POSSIBLE BUG? 

### ISSUE THREAD

**Issue by david08-08** [dgunning/edgartools#148]
Good afternoon, Dwight. I’m having trouble retrieving the stockholders equity statement using the XBRL Quarterly Financial Statement library. I pulled the last four quarterly filings for each company mentioned in the title/subject, but the CONDENSEDCONSOLIDATEDSTATEMENTSOFSTOCKHOLDERSEQUITY financial data isn’t importing to Excel, though the labels are. I’ve included a screenshot for HD. Could you run this and let me know if it’s an issue with my code? Thanks for your help and time. 

Thank you, 
David 
@dgunning 
<img width="1728" alt="Screenshot 2024-11-12 at 2 02 57 PM" src="https://github.com/user-attachments/assets/a8caa322-d3de-412a-922d-f4e4618d9d0e">

**Comment by dgunning** [comment]
I will take a look. I think I know the issue which mainly affects equity statements

**Comment by david08-08** [comment]
@dgunning Thank you, Dwight. Please let me know when this is closed. I appreciate your help. 

David

**Comment by david08-08** [comment]
@dgunning Good afternoon, Dwight. I was just wondering if you have a chance to look at this yet and when it would be fixed. Thank you.

**Comment by dgunning** [comment]
Should be fixed in 3.1.5

**Comment by david08-08** [comment]
@dgunning looks good Dwight. Thank you.

**Comment by dgunning** [comment]
Fixed
