### ISSUE TITLE
xbrl_data rich formatting errors

### ISSUE THREAD

**Issue by webbsledge** [dgunning/edgartools#150]
Easily demonstrated from the existing `Reading-Data-From-XBRL.ipynb` notebook, but behavior is exhibited in normal Python scripts as well.

<img width="943" alt="Screenshot 2024-11-13 at 11 28 46 PM" src="https://github.com/user-attachments/assets/0b44fd38-aef1-4945-86e0-ad72bdda8494">

**Comment by dgunning** [comment]
Fixed

**Comment by sledgeaw** [comment]
@dgunning Wonderful. Thank you!
