### ISSUE TITLE
how to loop over statement

### ISSUE THREAD

**Issue by onthegit** [dgunning/edgartools#151]
Hello, I am new to python, and I was wondering how to loop over Statement and get the label, concept, ,value,  and name (e.g us-gaap:DebtInstrumentCarryingAmount) ? Is this possible with this library?

**Comment by dgunning** [comment]
You can use `statement.get_dataframe()` and loop over the dataframe rows

```python
df = income_statement.get_dataframe()
for row in df.iterrows():
    print(row)
```

**Comment by onthegit** [comment]
@dgunning  thanks. it looks like the row does not contain the dimensions and other attributes. Is there a way to get them while looping over statements? Thank you.
