### ISSUE TITLE
13-HF: how to access Period of Report from the filing

### ISSUE THREAD

**Issue by mmistroni** [dgunning/edgartools#152]
Hi,
 not a bug but i am trying to find out how to access the Period of Report from a Form 13-HF

filings_13 = get_filings(2024, 1 , '13F-HR') 
dir(filings_13[0])

Kind regards
Marco

**Comment by dgunning** [comment]
Convert the filing to a `ThirteenF` object first
```python

>>> from edgar import *
>>> filings = get_filings(form="13F-HR")
>>> filing = filings[0]
>>> hr = filing.obj()
>>> hr.report_period
```

**Comment by mmistroni** [comment]
Thanks Dwight you can close issue
rgds
