### ISSUE TITLE
Is there a way to turn off rich Status spinner

### ISSUE THREAD

**Issue by chang-trivariate** [dgunning/edgartools#153]
Trying to use `get_by_accession_number` in a loop wrapped by tqdm progress bar (or any progress bar). But the `rich.Status` spinner inside the loop is interrupting the progress bar causing repeated bars printed out. Is there a recommended way to avoid this or turn off the the `rich.status` spinner?

![image](https://github.com/user-attachments/assets/7c00efae-42fd-4c4d-9414-897aefbb2d57)

Also wonder what is the source of CUSIP ticker mapping file - `ct.pq`? Is it a static file?

Thanks!

**Comment by dgunning** [comment]
Added a parameter `show_progress=False` to 3.2.4 that you can use to turn off the progress bar

`get_by_accession_number` does a search so can be slower that doing a filter
```python
filings.filter(accession_number=['0001888524-24-016584', '0001888524-24-016606'])
for filing in filings:
    ....
```

The cusip ticker file is a data file rebuilt roughly twice a month from the SEC's failure to deliver list. It's not critical to update to get the latest unless you absolutely never want to miss a new Cusip

**Comment by dgunning** [comment]
Fixed

**Comment by chang-trivariate** [comment]
Looks great thanks!
