### ISSUE TITLE
Form 4 Download

### ISSUE THREAD

**Issue by firmai** [dgunning/edgartools#156]
What is your approach for example to bulk download  3,4, and 5 filings ? I see you have a bulk section, but did no see these filings mentioned. 

```
from edgar import *

# Tell the SEC who you are
set_identity("Michael Mccallum mike.mccalum@indigo.com")
filings = get_filings(form=['4'], year=2020)
filing = filings[0]
```

I seem to be also particularly struggling to obtain the URLs in filings, for example, there should be aconvenient way to grab the xml and html URLs for all the filings here, so that we can start a convenient download operation on our side, this is easy to reconstruct for txt filings, but because of name uniqueness, not easy with xml and html, have you worked with this before? 

```
filings = get_filings(year,form="3")
df = filings.to_pandas()
```

**Comment by dgunning** [comment]
Edgartools allows you to get the home page of a filing, and the home page has the urls for the HTML, XML and other attachments

```python
# The filing homepage
filing.home

# The primary xml document
filing.home.primary_xml_document

# The primary xml document url
filing.home.primary_xml_document.url

# The primary html document
filing.home.primary_html_document

# The primary html document's url
filing.home.primary_html_document.url
```

Note that getting the home page requires an additional HTML request, but there are plans to improve this in a future version.

Even easier, you can just call it `.xml()` and `.html()` on a file to get the respective content. 
```python
filing.xml()

filing.html()
```

If you want the parsed version of a Form 4, Form 5, or Form 3 can just call `filing.obj()`.

```python
filing.obj()
```
