### ISSUE TITLE
Feature request: Item text parsing support for 10-K/Q

### ISSUE THREAD

**Issue by davelacy** [dgunning/edgartools#16]
First, excellent library. Well done! 👏  Thanks for creating this....

I'm curious to know if you plan to add text parsing support for 10-Ks and 10-Qs and other filings, much like you provided for 8-Ks?

Like the following:

![Image](https://github.com/dgunning/edgartools/assets/1942309/768450d8-cd24-43e6-8f8f-9dd386085d59)

On a side note, is there an easy way to convert the results above to JSON?

Cheers!

**Comment by dgunning** [comment]
Thanks for the feedback, I work hard at improving it.

I started doing a general way to split 10-Ks into items just like 8-Ks, but stopped to re-evaluate the approach.
 There is a better way to do it and I think I can get this coded soon

For the json output you can probably do this 
```
eightk = adobe_8K.obj()
item_json = [{'Item': item.item_num, 'Text': item.text} for item in eightk.items]
print(item_json)
```

**Comment by davelacy** [comment]
Excellent! Thanks, I'll give that a go and I look forward to future features 🚀
