### ISSUE TITLE
Finding a company CIK given its name

### ISSUE THREAD

**Issue by mmistroni** [dgunning/edgartools#160]
Hi Dgunning,
   is there a way to get a company cik given its name?
I am starting from this

company = Company("APPLE INC")

Many thanks
Marco

**Comment by dgunning** [comment]
Use `find`

```python
results = find("Apple Inc")

# This returns a CompanySearchResults so you have to select 1
results[0]
```

<img width="1297" alt="find2" src="https://github.com/user-attachments/assets/5ed4a8ff-834f-4561-b9d5-4ed237838aa3">
