### ISSUE TITLE
wiki for downloading data to a custom directory needs the env variable updated

### ISSUE THREAD

**Issue by rla3rd** [dgunning/edgartools#168]
the wiki has EDGARTOOLS_DATA_DIR,   it should be EDGAR_LOCAL_DATA_DIR

**Comment by dgunning** [comment]
Hey Rick, where is this `EDGARTOOLS_DATA_DIR` located - I can't find it

**Comment by rla3rd** [comment]
the wiki is out of date is all, was playing around seeing how i can can
make use of downloading bulk to speed up initialization of a django based
db.
https://github.com/dgunning/edgartools/wiki/DownloadingData#downloading-the-data

**Comment by dgunning** [comment]
John Friedman has a solution for [self hosting Edgar data ](https://medium.com/@jgfriedman99/how-to-host-the-sec-archive-for-20-month-da374cc3c3fb). I need a collaborator to work a backend for edgartools that uses it as an alternative to EDGAR

**Comment by rla3rd** [comment]
i've briefly spoken with john before. interesting, he's gotten much further
along since the last time i chatted with him.  That post is new, i should
start following him.  Are you going to self host it yourself or use his?
This is interesting because it sounds like it could really be a nice pds
alternative.  That subscription is expensive, you could charge a 1/4 of
what they do and be making some serious bank.  I don't know how much I can
contribute to something like this yet.  I'm still waiting for the fallout
of non-compete agreements to be dead (
https://www.ftc.gov/news-events/features/noncompetes).  I've got one in
place and contributing in any meaningful visible way could jeopardize my
employment. While I can work on my own code in obscurity, yours is starting
to become quite visible :).  But I digress, he's right the data is not that
big.  At work, we have all of edgar with no compression from pds in s3 and
the whole thing is approx 6 TB.  I can buy a mechanical drive to hold it
these days for approx $150.

**Comment by dgunning** [comment]
Closing as completed
