### ISSUE TITLE
S-3 issues

### ISSUE THREAD

**Issue by thegallier** [dgunning/edgartools#17]
Primary document and full submission text not working if you click the links. There is  info on homepage.  Cik 1145255 for example

**Comment by dgunning** [comment]
CIK 1145255 is HENNESSY ADVISORS INC  

There are 4 S-3 filings

╭───────── Filings for HENNESSY ADVISORS INC [1145255] ───────╮                                                                                                                                   
│       form   filed        accession_number       xbrl                                                                                      
│  ───────────────────────────────────                                                                                      │
│   0   S-3    2023-12-08   0001437749-23-034017                                                                                             
│   1   S-3    2020-12-08   0001104659-20-133251                                                                                            
│   2   S-3    2017-12-12   0001571049-17-008691                                                                                             
│   3   S-3    2015-02-06   0001144204-15-006742


For 0001437749-23-034017 (2023-12-08) the links were

│   🏠 Homepage               https://www.sec.gov/Archives/edgar/data/1145255/0001437749-23-034017-index.html                                 
│   📄 Primary Document       https://www.sec.gov/Archives/edgar/data/1145255/000143774923034017/hnna20231205_s3.htm                          
│   📒 Full Submission Text   https://www.sec.gov/Archives/edgar/data/1145255/000143774923034017/0001437749-23-034017.txt

I tested the links and they work.

 Now sometimes the link is displayed partially in the terminal or notebook depending on how wide the screen is.
 Can you screenshot the link you clicked on?

**Comment by thegallier** [comment]
get_by_accession_number("0000320193-20-34576")

gives

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>edgar/data/1680048/000110465923125109/0001104659-23</Key>
<RequestId>MYHVYHKS7ESJSEQ7</RequestId>
<HostId>43DYUvHa0FpHkFvw3rxyYmX8MkOiad4HSMOSd9M0ilWVd/D5rAb7yIj7g0Wrtu+fC61S3N1HUOE=</HostId>
</Error>

**Comment by dgunning** [comment]
This is not a valid accession number "0000320193-20-34576" - there needs to be six digits after the dash

Can you provide the link to the filing on the SEC website?

**Comment by thegallier** [comment]
if you run 

get_by_accession_number('0001104659-23-125109')

you will get a return value with links.  clicking the  links (except home page) does not work.  If you click home page and then click the link, that works.  However, I just noticed that this might be a display issue (so browser and screen size dependent as i see ... next to link).

**Comment by thegallier** [comment]
🏠 Homepage               https://www.sec.gov/Archives/edgar/data/1680048/0001104659-23-125109-index.html     │
│   📄 Primary Document       https://www.sec.gov/Archives/edgar/data/1680048/000110465923125109/tm2332430d1_s…   │
│   📒 Full Submission Text   https://www.sec.gov/Archives/edgar/data/1680048/000110465923125109/0001104659-23…   │
│                                                                                                              

See the home page is valid url.  the other 2 have icons and what looks like links but ... at the end.

**Comment by dgunning** [comment]
Ok got it. The links are displayed in a **rich** Table and **rich** tables truncate their output to fit the current display.
If you make your display (your console or notebook) is wider .. then the full link will display.

Nevertheless I will try to make it so that the full link displays, probably with a text overflow

**Comment by dgunning** [comment]
Released edgartools 2.6.2 that expands the area available to display links, and should make it much harder to get this issue.

It will not completely prevent it, because the truncating is in the rich library. The workaround to expand the console width, or ensure that the entire link is visible in a notebook
