### ISSUE TITLE
error from import edgar statement

### ISSUE THREAD

**Issue by GeoffreyBurger** [dgunning/edgartools#18]
Hi I'm getting an error at the initial import statement
from edgar import * 

error is:

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[5], line 1
----> 1 from edgar import *

File ~\AppData\Roaming\Python\Python311\site-packages\edgar\muniadvisors.py:14
     11 from rich.table import Table
     12 from rich.text import Text
---> 14 from edgar import Filing
     15 from edgar._party import Name, Address
     16 from edgar._rich import repr_rich

ImportError: cannot import name 'Filing' from 'edgar' (C:\Users\Geoffrey\AppData\Roaming\Python\Python311\site-packages\edgar\__init__.py)

**Comment by dgunning** [comment]
Hello, do you still have this issue?

**Comment by GeoffreyBurger** [comment]
Hi thanks for the follow up. I've been focused on a different project, and didn't rebuild my pip install. Will reply once I get back to this project.

**Comment by dgunning** [comment]
Closing. If it recurs, feel free to reopen
