### ISSUE TITLE
NFLX 10-K income statement is not parsed correctly

### ISSUE THREAD

**Issue by gchinna** [dgunning/edgartools#22]
NFLX 10-K filing income statement appears to be using different gaap tags and missing multiple facts from income statement after parsing.
https://www.sec.gov/ix?doc=/Archives/edgar/data/1065280/000106528023000035/nflx-20221231.htm#id2a4f0e6b6dd43c49a69044f9260d065_115
**"Total Revenue"** tag used in 10-K filing: us-gaap:Revenues

```
    incdf = Company("NFLX").get_filings(form="10-K").latest(1).obj().income_statement.income_statement_dataframe
    print(f"{incdf.to_markdown()}")
```
above code produces only the below three facts from NFLX 10-K filing.

|    | Fact                     | Value          |
|---:|:-------------------------|:---------------|
|  0 | Operating Income or Loss | $5,632,831,000 |
|  1 | Net Income               | $4,491,924,000 |
|  2 | Interest Expense         | $706,212,000   |

**Comment by dgunning** [comment]
Taking a look. Thanks

**Comment by dgunning** [comment]
Rewrote the Company Financials changing how it pulls information from the xbrl

```
filings = Company("NFLX").get_filings(form="10-K")
tenk = filings.latest(1).obj()
tenk
```

Here is NFLX's income statement

```
tenk.financials.income_statement
```
![Income Statement](https://github.com/dgunning/edgartools/blob/main/docs/images/nflx_income_statement.png?raw=true)

**Comment by dgunning** [comment]
Fixed
