### ISSUE TITLE
How to download submissio file

### ISSUE THREAD

**Issue by peiyaoli** [dgunning/edgartools#26]
Really appreciate you have created such an awesome library.

Here is one issue we came up with:

After I fetched attachment 
![Screenshot 2024-01-24 100034](https://github.com/dgunning/edgartools/assets/18466185/469c89a2-bd85-4112-8df1-b2796a3147a2)

I need to download last text file, here is my code:

```
with open("my_file.txt", "wb") as binary_file:
    submission_txt = filing.attachments[14].download()
    # Write bytes to file
    binary_file.write(submission_txt)
```
It showed error, can I resolve this issue?

**Comment by dgunning** [comment]
Do you have the accession number for the filing you are trying to download, so I can reproduce? 

The submission file is text not binary and so `open("my_file.txt", "w")` should work

Or download as string then `.encode('utf-8')` to convert to binary


Other ways

```python
from path lib import Path
Path('file.txt').write_bytes(filing.full_text_submission().encode('utf-8'))
```
To download an image file
```python
Path('image.jpg').write_bytes(filing.attachments[2].download())
```

**Comment by dgunning** [comment]
Please check if that solution works for you

**Comment by dgunning** [comment]
Closing this issue.
