### ISSUE TITLE
strip_ixbrl_tags breaks when name() is missing

### ISSUE THREAD

**Issue by hspak** [dgunning/edgartools#28]
edgartools runs into this XML parsing exception when name is missing in the XML

<img width="448" alt="Screenshot 2024-01-31 at 4 01 19 PM" src="https://github.com/dgunning/edgartools/assets/841216/06d4f27b-c8e5-4d42-85cc-c0fac431903a">
<img width="771" alt="Screenshot 2024-01-31 at 3 58 28 PM" src="https://github.com/dgunning/edgartools/assets/841216/b927caa9-281e-46c7-8981-4974321d1f7f">

Repro simple
```
import edgar

edgar.set_identity("id")
company = edgar.Company("HON")
filings = company.get_filings(form=["10-K"])
filings[0].text()  <-- throws here
```

Python: 3.11.6
Edgartools version: 2.7.2

**Comment by dgunning** [comment]
Taking a look. I am planning a release in the next day or so, will include a fix for this

**Comment by dgunning** [comment]
Release a fix in version 2.8.0. Can you update and retest

`pip install -U edgartools`

**Comment by dgunning** [comment]
Close as fixed

**Comment by hspak** [comment]
It appears fixed, thank you!
