### ISSUE TITLE
get_facts_for_namespace returns AttributeError

### ISSUE THREAD

**Issue by ilias-ant** [dgunning/edgartools#33]
### Problem

Per [README documentation](https://github.com/dgunning/edgartools?tab=readme-ov-file#get-company-facts):

```python
company = Company("SNOW")
company_facts = company.get_facts_for_namespace()
```
is expected to work - however `get_facts_for_namespace` returns an `AttributeError`.

### Minimum Reproducible Example

```shell
# e.g. tested it in Python 3.12.2
pip install edgartools==2.9.0
```
and then:
```python
from edgar import *

set_identity("Ilias Antonopoulos foobar@gmail.com")  # enter valid email here
company = Company("SNOW")
company_facts = company.get_facts_for_namespace()
```

### Screenshot

![image](https://github.com/dgunning/edgartools/assets/42189572/ed5b6bc7-6b84-49e8-9d12-c5438c1bb5b8)

p.s. happy to assist with its resolution if it's source code issue and not simply a documentation one :)

**Comment by dgunning** [comment]
Thanks a lot for this. I fixed the documentation to `company.get_facts()`
