### ISSUE TITLE
Not able to run EDGAR in Python 3.11.8

### ISSUE THREAD

**Issue by kchander92** [dgunning/edgartools#35]
I recently updated my Conda environment to version 24.1.2 and then updated Python to 3.11.8. Using pip, I installed EDGAR to get version 5.4.3.
![image](https://github.com/dgunning/edgartools/assets/101078824/aa5274d3-84c4-4c1a-9969-9118d2510248)

However, upon trying to import EDGAR and run setup, I got the following error:
![image](https://github.com/dgunning/edgartools/assets/101078824/a3a647f1-85fe-469e-a27d-02aa07eb279a)

What could be the cause of this? Thanks.

**Comment by dgunning** [comment]
Looks like you installed the wrong library. This library is called **edgartools**
```bash
pip uninstall edgar
pip install edgartools
```

Though after you install `edgartools` you still import it as `edgar`
`from edgar import *`
