### ISSUE TITLE
ability to load previously saved filings

### ISSUE THREAD

**Issue by ilias-ant** [dgunning/edgartools#36]
In the spirit of [ETL](https://en.wikipedia.org/wiki/Extract,_transform,_load), it would be beneficial for downstream applications of `edgartools` to be able to discretize company filings persistence (_e.g. in a storage backend like S3)_ and company filings parsing (_e.g. extracting the balance sheet data_) in order to engineer more flexible data pipelines.

The library right now provides the ability to persist a company filing (e.g. through `.full_text_submission()` on filing or through `.download()` on attachments) but - based on my experience as an application user - there doesn't seem to be a straightforward way to load a saved company filing and continue the parsing (e.g. `filing.obj()`) from there.

I suspect that this might not be the vision and philosophy of `edgartools` (_and i totally respect it_), just pitching the angle in order to discuss whether this resonates with you and the community.

**_p.s._** I really, really like how the library is designed! Kudos for the effort, this is monumental work! <3
**_p.s.2_** happy to help with the design / implementation of said feature (if it first passes feedback ofc)

**Comment by dgunning** [comment]
Thanks for this well written issue. I think it is a valid use case and I would like to make it more straightforward.

Do you mean 
- get a filing
- persist it
- restore it

Is this just for a `Filing` or a `Filings`

Let me know and we can collaborate on this

**Comment by ilias-ant** [comment]
Hello!

yes, this is what i had in mind.

I think `Filing` should suffice, since it's the only object (afaik) that is part of the `obj`'s signature.

```python
def obj(sec_filing: Filing) -> Optional[object]:
    ...
```

So, it comes down to sensible serialization / deserialization of the `Filing` object, right?

**Comment by dgunning** [comment]
Couple considerations

1. Protocol. 
Options are json, pickle. Pickle might be better
2. Filename
The accession_number is unique per filing so use a name like `0000000000-24-000001.pkl`
3. Directory
It probably does not make sense to save in the current directory so require a directory path to be passed in.
4. Cloud
Would saving to a directory cover cloud serialization?
5. Saving the `Filings`
In addition to saving `Filing` if you save and restore `Filings` you can retrieve a collection of filings which would be good for ETL

Thoughts
