### ISSUE TITLE
Rendering images when downloading HTML

### ISSUE THREAD

**Issue by paulommaia** [dgunning/edgartools#43]
When you use the .download() method, the attachments such as images aren't downloaded (and therefore, not rendered) in the downloaded HTML

Example:

```
cik = 'TSLA'

after = '2013-01-01'

filings = Company(cik).get_filings(form="8-K").filter(date=f"{after}:")

filings[0].attachments[1].url
```

This leads to https://www.sec.gov/Archives/edgar/data/1318605/000095017024046895/tsla-ex99_1.htm which is a slide-deck. 
The .download() method returns the HTML but the images are hosted **relative to the file URL** (e.g. https://www.sec.gov/Archives/edgar/data/1318605/000095017024046895/tsla-ex99_1s2.jpg). 

We can also find these images in the `filings[0].attachments` field, under GRAPHIC tag. 

What do you think would be the best pattern for the .download() method to include this? Or are there other alternatives you propose?

**Comment by dgunning** [comment]
How would you use case work .. do you want to download the html and the images so that they are relative to each other?

We can try to make the filling html and the attachments have consistent relative urls, I had that working once in an app I built on top of edgartools

**Comment by dgunning** [comment]
There are some libraries like pdfgen that convert html to pdf e.g.

```python
pdfgen.from_url('http://google.com', 'out.pdf')
```

Would that be better for your use case?

**Comment by paulommaia** [comment]
That could work - but unfortunately SEC blocks the access!

Your Request Originates from an Undeclared Automated Tool
To allow for equitable access to all users, SEC reserves the right to limit requests originating from
undeclared automated tools. Your request has been identified as part of a network of automated tools
outside of the acceptable policy and will be managed until action is taken to declare your traffic.

**Comment by dgunning** [comment]
I'm working on a way to render the filing as html so it can be piped into pdfgen.
We could also consider adding pdf generation in the library, as long as the new dependency is lightweight

**Comment by shaulimaya** [comment]
Hey!
Any update on that?

**Comment by dgunning** [comment]
Can you give me an example of how you would use this feature?

We could change `Attachments.download` to fix the paths in the HTML to the download folder. Then you could read the HTML in your program. We could also serve from a temporary web server. 

Thoughts?

**Comment by dgunning** [comment]
This is basically doable now by downloading attachments and opening a web server on the download location.
I'm going to add a serve() function in the next release that serves a filling with the linked images. Then it can be converted using a PDF library that accepts urls like pypdf.

**Comment by dgunning** [comment]
Can you try `filing.attachments.download(path)` to see if that meets your requirements?

**Comment by dgunning** [comment]
Closing a fixed
