### ISSUE TITLE
set_identity is not working

### ISSUE THREAD

**Issue by Rishabh634** [dgunning/edgartools#53]
![123](https://github.com/dgunning/edgartools/assets/165822970/f06ece61-bbc1-4c15-a1ee-cf8899fad24e)

it shows error "cannot import name 'set_identity' from 'edgar'" I tried using this on both jupter notebook & google colab. My python version on google colab is Python 3.10.12. & on jupyter is Python 3.11.7  . Please let me know how to resolve this.         Edit: working now

**Comment by dgunning** [comment]
Can you send me a link to the collar notebook?

Also try 

import edgar
print(dir(Edgar))

and tell me what you get

**Comment by homanp** [comment]
@Rishabh634 make sure poetry or pip didn't install another package called `edgar`.

**Comment by Rishabh634** [comment]
It's working now, sorry for the trouble.
