### ISSUE TITLE
Fail to Get Filings for a Specific Year

### ISSUE THREAD

**Issue by BeitianMa** [dgunning/edgartools#54]
I get the expected result when I run
```
filings = get_filings(2023, 1)
```
It finishes in about 7~8 secs on my laptop. However, when I run
```
filings = get_filings(2023)
```
the code runs indefinitely. I have to write a for loop to get the filings for each quarter
```
filings_list = []
for i in range(1,5):
    filings_list.append(get_filings(2023, i))
```
it takes 24~25 secs to finish. My Python version is 3.10.14 and I am using edgartools==2.19.2. I am not sure if this is a bug or if I am doing something wrong. I would appreciate any help. Thank you.

**Comment by dgunning** [comment]
Would you be able to run your code in a Google Colab notebook? I'm unable to reproduce in mine

https://colab.research.google.com/drive/17_Fb4Kj2soynApn3tLZKZrTvz3M4pH7n?usp=sharing

Alternatively, try upgrading to 2.22.0 .. the http request code is rewritten in that version

**Comment by dgunning** [comment]
Close due to inactivity
