### ISSUE TITLE
Some line items are missing in balance sheet report

### ISSUE THREAD

**Issue by unparadise** [dgunning/edgartools#57]
Thank you for building and sharing such a useful library!

While testing it, I noticed that some line items under current assets are missing in the balance sheet report when compared to the interactive data on the sec.gov website (Please see images pasted below).

![image](https://github.com/dgunning/edgartools/assets/6435661/3a8c8d81-02e6-4294-b386-77c27cf74c3a)
![image](https://github.com/dgunning/edgartools/assets/6435661/0b552f09-7324-4e2a-92df-bc1fa47615be)

This issue repros with other companies (E.G. MSFT). Is this behavior by design?

Thank you very much!

**Comment by dgunning** [comment]
When I implemented this feature (twice) I did it against a set of a few company financials .. did not know about this interactive feature. Now I know thanks. I will implement against  spec

**Comment by dgunning** [comment]
Release 2.24.1 with fixes for missing balance sheet items.

<img width="682" alt="apple_balancesheet" src="https://github.com/dgunning/edgartools/assets/1523271/baad250f-cf21-4191-984d-e10962583c98">

**Comment by unparadise** [comment]
@dgunning Thank you for adding the additional values, Dwight! Really appreciate it. I have noticed that the same issue exists for the income statement as well. Should I create another issue to track that?
