### ISSUE TITLE
Balance Sheet

### ISSUE THREAD

**Issue by jdy214** [dgunning/edgartools#58]
Similar issue experiences same items are missing from balance sheet.  Otherwise very intuitive design

**Comment by dgunning** [comment]
Fixing the balance sheet now.

I don't see Marketing Expenses here .. do you mean Sales, General and Administrative Expenses? 
<img width="630" alt="apple-incomestatement" src="https://github.com/dgunning/edgartools/assets/1523271/b596233c-498a-412d-a921-651cf64ea039">

**Comment by jdy214** [comment]
Hi Dwight,

Thank you for following up.  I may have not been clear on the post,  there
is an issue with the balance sheet and then a sperate issue with the
Marketing Expenses which appears on the income statement problem.  You see
it for instance if you look at AAPL or MBLY, for two examples.  In the AAPL
example Marketing shows as a line item, even though it does not appear as
an item on AAPL's income statement.  For Mobile Eye (MBLY) it shows as a
line item but does not seem to be picking up any values.  This happens with
a few other of the income statement items.  Rather than reading the file
and retrieving the line item titles, its seems that it is searching for
pre-defined line items like :Marketing expense".

My knowledge of coding is limited, but if there is any way I can help
improve edgar tools, I would be happy to help.

Very Truly,
Justin

**Comment by dgunning** [comment]
You are right .. it could be enhanced to not show empty line items.

Thanks, working on it this week

**Comment by jdy214** [comment]
For AAPL the values is empty, however for MBLY there are values there it is
not picking them up

Justin

**Comment by dgunning** [comment]
Hi Justin, 

I uploaded a screenshot of the financial statements for Apple along with the xbrl and asked ChatGPT to generate the mappings here 

https://github.com/dgunning/edgartools/tree/main/data/financials

Take a look, maybe you can see if they are correct and would work for other companies

**Comment by jdy214** [comment]
Sure I will have a look at it tonight!

This could really be a stellar alternative to the sec's official scraping
platform.

Justin

**Comment by jdy214** [comment]
Hi Dwight,

I see the issue is that there are simply too many variations of the
contextRef used in the xml files.  So except for the subtotal the companies
do not use the same references for the line items.

Do you think there is an efficient way to recategorize groups of the
contextRef under a more general line item name? I believe this is how
CapitalIQ does it on their end.


Justin

**Comment by dgunning** [comment]
That's a related issue but not the core one.  

The missing data is mostly there for MBLY in the default context but they weren't mapped because the reference companies I used initially are different company types and didn't have those facts.
Companies can choose to map data to different fact names. 

I'm making progress today on the core issue and should have a release coming out of this weekend. 

The second issue is as you say the context issue which has company specific data. I'm working on a way to map these and thanks for the suggestion I'll look into it.

Dwight

**Comment by dgunning** [comment]
Release 2.24.1 with fixes for missing balance sheet and income statement items.

**Comment by jdy214** [comment]
Just tried it looks great, can I ask conceptually how did you resolve the
issue?

 I ran through some solutions myself using chatGPT, but I couldnt figure
out how do you determine which references belong to the income statement,
(versus income statement notes or some alternate source in the xml file)?
What marker or tag lets you know that a certain fact belong to the income
statement vs. balance sheet vs. the rest of the file, where other items
have xbrl tags as well?

Very Truly,
Justin

**Comment by dgunning** [comment]
I uploaded a screenshot of the financials on the sec site, and the XBRL facts csv to ChatGPT and asked it to produce a mapping

**Comment by jdy214** [comment]
Hello,

I noticed there was an update for edgar.  Now that I have updated, I am
unable to import the module, seems to be an issue with accessing the xbrl
portion?

Do you have any solutions to suggest to resolve?

Very Truly,
Justin
