### ISSUE TITLE
Accessing 'ITEM 1A': {'Title': 'Risk Factors',}

### ISSUE THREAD

**Issue by mmistroni** [dgunning/edgartools#59]
Hello
 this is not an issue but i would like to know how to access Risk Factors out of the XBRL?
i cannot find any methods to do that?

Kind regards
marco

**Comment by dgunning** [comment]
Risk Factors from the XBRL or Risk Factors from the 10-K/10-Q

**Comment by mmistroni** [comment]
Hi, From 10-K / 10-Q, but i believe the commentaries are not included in XBRL so i guess i have to find a better way to get it

**Comment by vishwasg217** [comment]
Looking for something similar. Would love to have feature to directly access each item's content in 10-K report, preferably in html/markdown

**Comment by mmistroni** [comment]
Hello
  one thing  you can  try -  i tried with form 8-K and DEF 14A -  is to get
the text() from the filing and look for specific sections.
get the substring and give it 'to the bot' to extract it.....
something like the code below

-i havent treid with 10K as 10K text is much longer and convoluted.... i'll
try this week but if you have time pls give it a go and let me know

hth
 Marco

company = Company("WMT") proxies = company.get_filings(form="DEF 14A")
random_proxy = proxies[0] ## there is too much info. so to narrow downt the
scope we will look for well defined sections txt = random_proxy.text()
start = txt.find('EXECUTIVE COMPENSATION TABLES') exec_section_start =
txt[start:] end = exec_section_start.find('Deferred Compensation Plans') #
This normally comes after the compensation table mgmt_text =
exec_section_start[0:end] #print(mgmt_text) response =
model.generate_content(f"Can you extract the names of persons listed in
this text:{mgmt_text}") print(response.text)

**Comment by mmistroni** [comment]
Vishwas, there's a way

you can get the full text submission from here

company = Company("WMT")
tenks = company.get_filings(form="10-K")
tenks[0].full_text_submission()



i wrote code some time ago to parse 10k , identify sections and extract
sentiment
give me couple of days to resurrect it and i'll repost to this threada.
it's nothing too complicated,just some regexes etc

**Comment by mmistroni** [comment]
Thanks, that works perfectly... should have tried myself before making any
noise :(

**Comment by dgunning** [comment]
Closed as fixed
