### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by crunchanalytic** [dgunning/edgartools#62]
Import error

from edgar import *
This worked well 2 days ago.  Now I get this:

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[1], line 1
----> 1 from edgar import *

File ~\anaconda3\Lib\site-packages\edgar\__init__.py:9
      6 from functools import partial
      7 from typing import Optional, Union, List
----> 9 from edgar.entities import (Company,
     10                             CompanyData,
     11                             CompanyFacts,
     12                             CompanySearchResults,
     13                             CompanyFilings,
     14                             CompanyFiling,
     15                             Entity,
     16                             EntityData,
     17                             find_company,
     18                             get_entity,
     19                             get_company_facts,
     20                             get_company_tickers,
     21                             get_entity_submissions,
     22                             get_ticker_to_cik_lookup,
     23                             get_cik_lookup_data)
     24 from edgar._filings import (Filing,
     25                             Filings,
     26                             FilingHeader,
   (...)
     32                             get_by_accession_number,
     33                             FilingHomepage)
     34 from edgar.core import (edgar_mode,
     35                         CRAWL,
     36                         CAUTION,
     37                         NORMAL,
     38                         get_identity,
     39                         set_identity)

File ~\anaconda3\Lib\site-packages\edgar\entities.py:17
     14 from rich.panel import Panel
     15 from rich.text import Text
---> 17 from edgar._filings import Filing, Filings, FilingsState
     18 from edgar._rich import df_to_rich_table, repr_rich
     19 from rich import box

File ~\anaconda3\Lib\site-packages\edgar\_filings.py:36
     33 from rich.text import Text
     35 from edgar._markdown import html_to_markdown, text_to_markdown
---> 36 from edgar._party import Address
     37 from edgar._rich import df_to_rich_table, repr_rich
     38 from edgar._xbrl import FilingXbrl

File ~\anaconda3\Lib\site-packages\edgar\_party.py:12
     10 from edgar._rich import repr_rich
     11 from edgar._xml import child_text, child_value
---> 12 from edgar.core import IntString
     14 __all__ = [
     15     'Address',
     16     'Issuer',
   (...)
     20     'get_addresses_as_columns'
     21 ]
     24 class Address(BaseModel):

File ~\anaconda3\Lib\site-packages\edgar\core.py:20
     18 import pyarrow as pa
     19 import pyarrow.compute as pc
---> 20 from charset_normalizer import detect
     21 from fastcore.basics import listify
     22 from rich.logging import RichHandler

File ~\anaconda3\Lib\site-packages\charset_normalizer\__init__.py:23
      1 """
      2 Charset-Normalizer
      3 ~~~~~~~~~~~~~~
   (...)
     21 :license: MIT, see LICENSE for more details.
     22 """
---> 23 from charset_normalizer.api import from_fp, from_path, from_bytes, normalize
     24 from charset_normalizer.legacy import detect
     25 from charset_normalizer.version import __version__, VERSION

File ~\anaconda3\Lib\site-packages\charset_normalizer\api.py:10
      7     PathLike = Union[str, 'os.PathLike[str]']  # type: ignore
      9 from charset_normalizer.constant import TOO_SMALL_SEQUENCE, TOO_BIG_SEQUENCE, IANA_SUPPORTED
---> 10 from charset_normalizer.md import mess_ratio
     11 from charset_normalizer.models import CharsetMatches, CharsetMatch
     12 from warnings import warn

File ~\anaconda3\Lib\site-packages\charset_normalizer\md.py:5
      2 from typing import Optional, List
      4 from charset_normalizer.constant import UNICODE_SECONDARY_RANGE_KEYWORD
----> 5 from charset_normalizer.utils import is_punctuation, is_symbol, unicode_range, is_accentuated, is_latin, \
      6     remove_accent, is_separator, is_cjk, is_case_variable, is_hangul, is_katakana, is_hiragana, is_ascii, is_thai
      9 class MessDetectorPlugin:
     10     """
     11     Base abstract class used for mess detection plugins.
     12     All detectors MUST extend and implement given methods.
     13     """

ImportError: cannot import name 'COMMON_SAFE_ASCII_CHARACTERS' from 'charset_normalizer.constant' (C:\Users\crunc\anaconda3\Lib\site-packages\charset_normalizer\constant.py)

********

I assume this is affecting other users?

Thank you for your work.
-m

**Comment by dgunning** [comment]
Hello,

What does this return


```bash
pip show charset-normalizer
```

**Comment by crunchanalytic** [comment]
Thank you for your prompt reply.  I am updating my system, so I'm unable to
check right now.

PS - I wish I would have noticed that you added the more precise balance
sheet items, before I created them for myself last week!  LOL!

**Comment by crunchanalytic** [comment]
Is this helpful at all?
Thank you again for your trouble.
-mark

**Comment by dgunning** [comment]
Sorry, what's helpful .. did you add something to the issue thread?

**Comment by crunchanalytic** [comment]
Sorry, no.  I emailed you a screenshot of the show charset-normalizer, you
asked for.

**Comment by dgunning** [comment]
I don't see the screenshot in the email chain

**Comment by dgunning** [comment]
Can you show me the result of

```
pip show charset-normalizer
```

**Comment by radhika3558** [comment]
Hello,

Is this what you mean? 
<img width="1000" alt="Screenshot 2024-06-17 at 6 10 12 PM" src="https://github.com/dgunning/edgartools/assets/150712105/7692980a-8b2f-4f1c-af06-385e8e2323e7">

**Comment by dgunning** [comment]
Thanks. I will release a new version maybe tomorrow without charset-normalizer

**Comment by radhika3558** [comment]
Thank you so much!

**Comment by dgunning** [comment]
Released 2.24.3. Please try it and let me know

**Comment by radhika3558** [comment]
Still having trouble importing
<img width="1000" alt="screenshot" src="https://github.com/dgunning/edgartools/assets/150712105/742e5809-063f-4199-9bcc-efb79f39d27b">

**Comment by dgunning** [comment]
You might have another package shadowing edgartools.

Try

```
pip uninstall edgar 
pip install -U edgartools

```

**Comment by radhika3558** [comment]
That helped! Thank you for being so responsive and creating edgartools!

**Comment by dgunning** [comment]
Great. Closing as fixed
