### ISSUE TITLE
When will the API data be updated?

### ISSUE THREAD

**Issue by Karie0910** [dgunning/edgartools#63]
I am working on downloading yesterday's N-PORT files.
There is data on the sec website.
![image](https://github.com/dgunning/edgartools/assets/172482849/b1f408b7-ed4d-4068-b567-1cd7af3d1bde)

My code is like:
`filings = get_filings(filing_date='2024-06-18', form="NPORT-P", amendments=True)`

However, it returns Nothing.

I am wondering when will the data be updated? Thank you!

**Comment by dgunning** [comment]
The SEC filing indexes are published around 10:45 PM EST nightly. This is what is returned by `get_filings`

To get the most recent filings not yet published in the SEC filing index use `get_latest_filings()`

I will think about merging the two API calls maybe with a parameter. I should also make it clearer in the docs

**Comment by dgunning** [comment]
Closed
