### ISSUE TITLE
How do i extract a specific section of a form?

### ISSUE THREAD

**Issue by gopi-tookitaki** [dgunning/edgartools#66]
For example, if in a form 10-k how do i extract section 5 only

**Comment by dgunning** [comment]
Convert the 10-K filing into a TenK Data Object
```python

tenk = filing.obj() 
tenk["Item 5"]

```

**Comment by baskargopinath** [comment]
Thanks, what are u using to extract the sections?

**Comment by dgunning** [comment]
Pretty complicated code. I can explain but it would be a blog article

**Comment by gopi-tookitaki** [comment]
@dgunning can u say the high level approach, how u chunk it based on sections?

**Comment by gopi-tookitaki** [comment]
also if the documet item is 5.02, if i do tenk["Item 5"] it doesnt work it has to be exactly 5.02. is there any workaround for this? for e.g if i wanna take 100 companies and extract all their section 5's from the 10k

**Comment by dgunning** [comment]
Try

```python
item_5s = [item 
           for item in tenk.items 
           if item.startswith("Item 5")]
```

**Comment by baskargopinath** [comment]
@dgunning in item 7  (MD & A) of the 10k, there is a section called Revenue recognition, but i cant seem to extract out that section, is it possible to do with ur library?

**Comment by dgunning** [comment]
Can you give me an example filing with the Revenue Recognition section?

**Comment by amitgandhinz** [comment]
similar to this question, how can I extract Net Sales by Category from the 10Q/10K ?  The income_statement only has the net amounts, and I dont see a way to get at the breakdown which is typically included as a note in the 10Q.

![image](https://github.com/user-attachments/assets/7dec84c1-aaf1-4659-bc55-c3309c351804)

**Comment by amitgandhinz** [comment]
after posting this question, I somehow managed to figure it out lol.  This is what I was able to do (let me know if there is an easier way)

`
            # ----
            # Extract detailed revenue items
            # ----
            revenue_sources = []
            facts = financials_xbrl.facts.data
            # Group by 'dimensions' and get the latest period for each dimension
            latest_rows = facts.groupby('dimensions').head(1)

            for index, row in latest_rows.iterrows():
                dimensions_str = row.get("dimensions", "{}")
                try:
                    dimensions_dict = ast.literal_eval(dimensions_str) if isinstance(dimensions_str, str) else dimensions_str
                except (ValueError, SyntaxError):
                    dimensions_dict = {}
                            
                product_dimension = dimensions_dict.get("srt:ProductOrServiceAxis") if isinstance(dimensions_dict, dict) else None

            
                if row["namespace"] == "us-gaap" and row["fact"].startswith("Revenue") and product_dimension is not None and product_dimension.startswith(symbol.lower() + ":") :
                    revenue_sources.append({
                        "name": product_dimension.replace("Member", "").replace(f"{symbol.lower()}:", ""),
                        "value": row["value"],
                    })
            # ----
            # end detailed revenue items
            # ----
`

**Comment by amitgandhinz** [comment]
Thanks for the great work you are doing here @dgunning !  

So I found some edge cases when reading those fields above - NVDA (and others) will have parent rows (eg DataCenter).  Others have subtotals.  But I can't tell them apart when reading them in. I dont want to read those totals in as it results in double counting the numbers. Any ideas on how to filter them out?

![image](https://github.com/user-attachments/assets/83d78a92-708b-4e1b-a9c7-884a3c3f86a2)

**Comment by dgunning** [comment]
Redirecting all questions related to financial data extraction to [Issue 74: Financial Extraction from XBRL](https://github.com/dgunning/edgartools/issues/74)

**Comment by dgunning** [comment]
Closing. Questions can be raised as discussions
