### ISSUE TITLE
Financials Extraction from XBRL

### ISSUE THREAD

**Issue by dgunning** [dgunning/edgartools#74]
Version 3 of XBRL financials

1. Rewrite Financial extraction from XBRL
2. Create a comprehensive test harness 
3. Document Financials V3

**Comment by dgunning** [comment]
Progress so far
<img width="650" alt="GDFinancials" src="https://github.com/user-attachments/assets/bd442cc8-1158-40de-a238-75b975fa71b9">

**Comment by dgunning** [comment]
Note from a user
Hey,

If this helps, here are the entry points from the FASB taxonomy that group the line items in the mandatory filing statements:

https://xbrlview.fasb.org/yeti/resources/yeti-gwt/Yeti.jsp#tax~(id~174*v~10231)!con~(id~5267870)!net~(a~3474*l~832)!lang~(code~en-us)!path~(g~99043*p~0)!rg~(rg~32*p~12)

**Comment by dgunning** [comment]
@emestee what do you know about standardized statements vs as-reported statements? Do you know what defines the standard concepts that all companies include in their statements?

**Comment by amitgandhinz** [comment]
circling back here as ive been playing with the new upgrades.  Thanks for this - looks like a lot of work went into the rewrite.

Were you able to pull in the productMembers as referenced here https://github.com/dgunning/edgartools/issues/66#issuecomment-2243569825

I have been trying to pull in the concepts that feed into the Revenue Sales, but still can't figure that out correctly.

The is the code snippet I have (eg for the AAPL XBRL instance)

```
# ----
                # Extract detailed revenue items
                # ----
                revenue_sources = []
                
                rev_dimensions = instance.dimensions
                rev_dimension_value = rev_dimensions['srt:ProductOrServiceAxis']
                facts = rev_dimension_value.get_facts()

                period_date_str = latest_date.strftime('%Y-%m-%d')
               
                # get the facts for this latest period
                latest_period_facts = facts[facts['end_date'] == period_date_str][facts["duration"] == "3 months"]
                
                for index, row in latest_period_facts.iterrows():
                    if row.concept.startswith("us-gaap:Revenue"):
                        print(row.value, row.concept, row.dimensions)
                
```

Running this against AAPL Q2 10Q, I get the following facts:

```
61564000000 us-gaap:RevenueFromContractWithCustomerExcludingAssessedTax {'srt:ProductOrServiceAxis': 'us-gaap:ProductMember'}
24213000000 us-gaap:RevenueFromContractWithCustomerExcludingAssessedTax {'srt:ProductOrServiceAxis': 'us-gaap:ServiceMember'}
39296000000 us-gaap:RevenueFromContractWithCustomerExcludingAssessedTax {'srt:ProductOrServiceAxis': 'aapl:IPhoneMember'}
7009000000 us-gaap:RevenueFromContractWithCustomerExcludingAssessedTax {'srt:ProductOrServiceAxis': 'aapl:MacMember'}
7162000000 us-gaap:RevenueFromContractWithCustomerExcludingAssessedTax {'srt:ProductOrServiceAxis': 'aapl:IPadMember'}
8097000000 us-gaap:RevenueFromContractWithCustomerExcludingAssessedTax {'srt:ProductOrServiceAxis': 'aapl:WearablesHomeandAccessoriesMember'}
```

The problem is that the us-gaap:ProductMember actually represents the total of all the individual product lines, so I end up double counting the product values.

Like, how do you determine that the apple:* members are part of the productMember, while the serviceMember is on its own without any nesting?

I want this product breakdown to work for any 10-Q so I can present where a companies incoming revenue comes from.

**Comment by dgunning** [comment]
You can see the  dimensions using the `dimensions` attribute
<img width="941" alt="instance_dimensions" src="https://github.com/user-attachments/assets/6609a274-cd52-4c9a-bb84-7cc5c47ee474">

And you can query by dimensions

<img width="843" alt="query_facts" src="https://github.com/user-attachments/assets/fa5f59e0-95f2-4c5f-ad17-fce95a50969c">

**Comment by emestee** [comment]
> @emestee what do you know about standardized statements vs as-reported statements? Do you know what defines the standard concepts that all companies include in their statements?

I actually don't know, I imagine it is SEC regulation derived from federal law and incorporating FASB rules. I also don't think it should matter. SEC filings are validated upon submission and can be assumed to be compliant with technical requirements (otherwise the SEC parser will reject the filing). You should not assign any specific meaning to any items in the statement, other than their relationships to parent items, if any.

**Comment by amitgandhinz** [comment]
thats kind of what im doing where I use this library to pull in the data but then standardize things into my own fields.

You prev had a version of that in your old income statement code, but the challenge is getting a mapping of all the fields into something.

**Comment by amitgandhinz** [comment]
> You can see the dimensions using the `dimensions` attribute <img alt="instance_dimensions" width="941" src="https://private-user-images.githubusercontent.com/1523271/358238982-6609a274-cd52-4c9a-bb84-7cc5c47ee474.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzNzU5NTksIm5iZiI6MTcyNDM3NTY1OSwicGF0aCI6Ii8xNTIzMjcxLzM1ODIzODk4Mi02NjA5YTI3NC1jZDUyLTRjOWEtYmI4NC03Y2M1YzQ3ZWU0NzQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjNUMDExNDE5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTNiZTQ0ODFhYmQ0NDJiN2FhNDFiNzg4MzlmYzlmYTcyYzk5ZTIwNWUzMTUwNTRlMzYxZThmZTgwMzA2NzY1YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.mNY8MsAy99Ei81RlJw9yFuTXgawHBeCjEVLvNi2kRTY">
> 
> And you can query by dimensions
> 
> <img alt="query_facts" width="843" src="https://private-user-images.githubusercontent.com/1523271/358239551-fa5f59e0-95f2-4c5f-ad17-fce95a50969c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzNzU5NTksIm5iZiI6MTcyNDM3NTY1OSwicGF0aCI6Ii8xNTIzMjcxLzM1ODIzOTU1MS1mYTVmNTllMC05NWYyLTRjNWYtYWQxNy1mY2U5NWE1MDk2OWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjNUMDExNDE5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NThjMTU3ZmIyZTNkYmI3NGFiYWRkMTBlYjg3YjJmYTA0Nzk3NDlkMzY4NWVkNDgxOGI3ODMwMGE5YTA5NTcwMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ahWCwLZ6Hm4SJEhFEZRk0v2gogkPO-VU695K4aHDJYU">

So with this, I am already getting the aapl:* dimensions.  But see how there is also the 'us-gaap: ProductMember' in the srt:ProductOrServiceAxis.  This ProductMember happens to be the sum of all the aapl dimensions.  Meanwhile the ServicesMember in this example doesn't have sub items.  Is there a way to know if a dimension is a total of other sub items (when you pull up the xbrl viewer on the sec site the items get indented so I assume the info is somewhere).

My use case is to be able to pull the product revenue sources generically for all 10K/10Q imports, so not necessarily Apple specific.

**Comment by Ahmedmagdy31** [comment]
> thats kind of what im doing where I use this library to pull in the data but then standardize things into my own fields.
> 
> You prev had a version of that in your old income statement code, but the challenge is getting a mapping of all the fields into something.

I'm struggling in this standardization now, would you please share the approach or some code to give me an idea? --I'm new to financial data and SEC but want to standardize financial statements for many companies. @amitgandhinz

**Comment by Colem19** [comment]
The new version is working much better on the financials statements! Thanks a lot for that! 

I think there is a small thing that could be highly improved in the cash flow statement. If I look at Apple, it seems like a lot of the lines are positive instead of being negative (like Share repurchases).

**Comment by david08-08** [comment]
@Colem19 @dgunning The statements are great; Dwight has done a great job. You are right though, good eye on identifying this issue. As an example I pulled (ULTA)'s most recent 10-Q via the TENQ-Class and I have identified a few more line items that either should have a negative output , positive output or its in reverse order (meaning 2024 should be positive and 2023 should be a negative). @dgunning do you anticipate that this will be fixed or is something that is fixable? 
<img width="618" alt="Screenshot 2024-09-11 at 9 21 54 AM" src="https://github.com/user-attachments/assets/e4c2f32c-1dd4-444c-85b6-9f66f58433ad">

**Comment by david08-08** [comment]
@Colem19 @dgunning To be clear I highlighted in yellow what should be negative for both years. And I commented what should be reversed and what should be positive.

**Comment by dgunning** [comment]
I verified and most values are in the right direction
<img width="907" alt="UltraBeautyCashFlow" src="https://github.com/user-attachments/assets/5f2b6ada-0cbc-4d0b-a686-c0a3031f9b07">

Deferred Income Tax does not match the Filing table in the HTML. 

The raw value does not match in the XBRL instance file but I suspect that there seems to be a bug in the XBRL calculation file. 

<img width="856" alt="UltraBeautyXbrl" src="https://github.com/user-attachments/assets/ef07c0b2-820e-4bce-94cd-3abd3a4a7003">

The calculation files usually have weights of -1 for negative values but it is missing in this case. 
<img width="1402" alt="weight" src="https://github.com/user-attachments/assets/edfcab57-cfe4-40d0-b6fa-cf6e669d082e">

Not much the code can do in this case

**Comment by dgunning** [comment]
Closing as fixed
