### ISSUE TITLE
Taking a long time

### ISSUE THREAD

**Issue by msharifbd** [dgunning/edgartools#75]
Hi, 
When I try to parse thousands of 10K for a given year, it takes too long to parse. Below is a sample of my code. 

Is there any way to speed up the process?

```
import pandas as pd
from edgar import * # edgartools         2.27.0 

# Tell the SEC who you are
set_identity("My Name myemail@outlook.com")
filings2 = get_filings(form='10-K', amendments=False, filing_date="2022-12-15:2023-12-14") 

filings2_df = filings2.to_pandas()

# Create a list to store the Item 1A (Risk Factors), 7 (MDA), and search "cybersecurity" text

item1c_texts = []
for n, filing in enumerate(filings2):
    url = filing.document.url
    cik = filing.cik
    filing_date = filing.header.filing_date,
    reporting_date = filing.header.period_of_report,
    comn = filing.company
    

    # Extract the text for Item 1c
    TenK = filing.obj()
    
    # Bypass None values
    try:
        item1a_text = TenK['Item 1A']
        item7_text = TenK['Item 7']

    except:
        item1a_text = None
        item7_text = None


    # Append the data to the list
    item1c_texts.append({
        'CIK': cik,
        'Filing Date': str(filing_date),
        'Item 7 Text': item7_text,
        'Item 1a Text': item1a_text,
        'url': url,
        'reporting_date': str(reporting_date),
        'comn': comn
    })

# Create a DataFrame from the Item 1c text data
item1c_df = pd.DataFrame(item1c_texts)
```

**Comment by dgunning** [comment]
Hi,

What is your current timing? That date range returns 7,400 filings and assuming it takes 1.5 seconds each that amounts to 3 to 4 hours, which is reasonable for downloading a years worth of 10-K.

That being said your code could be optimized further but since on average it takes .75 seconds to download the HTML itself, you'd be saving max 50%.

Suggestions though
1. Move the main part of the function into it's own function  that is called by the loop
2. Optimize this function separately
3. Change the function to download the item7 text to separate folders, then. accumulate the results in the dataframe. This avoid having 7000 chunks of HTML in memory 

I'm pretty busy at the moment but will see if I can take another look at this tomorrow

**Comment by benobytes** [comment]
@msharifbd Something you may want to try as an alternative, would be to use [threads](https://docs.python.org/3/library/concurrent.futures.html).

```py
from concurrent.futures import ThreadPoolExecutor, as_completed
from edgar import get_filings, set_identity

set_identity("My Name myemail@outlook.com")

filings = get_filings(form='10-K', amendments=False, filing_date="2022-12-15:2023-12-14") 

# Sample 10 filings to export as an example
df = filings.sample(n=10)

# Move the functionality out into a per row basis
def extract_fields(filing):
    filing_parsed = filing.obj()
    try:
        item1a_text = filing_parsed['Item 1A']
        item7_text = filing_parsed['Item 7']
    except:
        item1a_text = None
        item7_text = None
    return {
        "CIK": filing.cik,
        "Filing Date": filing.header.filing_date,
        "Reporting Date": filing.header.period_of_report,
        "Item 1A Text": item1a_text,
        "Item 7 Text": item7_text,
        "URL": filing.document.url,
        "Company": filing.company
    }

# item1c_texts = [extract_fields(i) for i in filings] # instead of this, run threads
item1c_texts = []

with ThreadPoolExecutor(max_workers=10) as executor:
    futures = [executor.submit(extract_fields, filing) for filing in df]
    for future in as_completed(futures):
        item1c_texts.append(future.result())
```

Another thing you can do is make sure your python version is latest, as python is constantly performance improvements. 

Following up @dgunning, 10-K files are typically quite large, and this dataset returns 7394 filings. Assuming that each primary document is ~2-3mb, you are looking at ~18.48 gigabytes of filings to download and process. So taking a long time would be expected.

**Comment by dgunning** [comment]
Careful with threading as you may get `TooManyRequests` and get blocked for 10 minutes.

The library uses a throttler that limits all requests to 10 per second. You can use an annotation to throttle your function as follows. Conservatively I have set requests per second to 2 below, because I haven't been able to push very high against the SEC .. I'm not sure how they are measuring 10 per second.

```python
from edgar.httprequests import throttle_requests
@throttle_requests(requests_per_second=2)
def extract_fields():
   ...

```

**Comment by benobytes** [comment]
I have been able to perform ~9ish requests per second without getting throttled. I've used both [rate_limit](https://pypi.org/project/ratelimit/) and [pyrate-limiter](https://pypi.org/project/pyrate-limiter/) without any issues in the past. I do have some scripts that download like this and haven't experienced issues. Perhaps they use a leaky bucket algorithm?

**Comment by msharifbd** [comment]
@dgunning Actually just to download for March, it takes more than 5 hours. If I run the code for whole year, after several hours sometimes it does not work and break and shows reasons something related to connection. It would be great if you can take a look at your convenient.

**Comment by msharifbd** [comment]
@benobytes Thanks for your suggestion. I am trying to run your code and let's see how long does it take?

**Comment by msharifbd** [comment]
@benobytes I ran your code for February 2022 and after running 2 and a half hours, it shows the following errors - 

```

ReadTimeout: The read operation timed out
File c:\Users\mshar\OneDrive - Southern Illinois University\POSITRON_different_files\ParseTenK\Lib\site-packages\httpx\_transports\default.py:69, in map_httpcore_exceptions()
     68 try:
---> 69     yield
     70 except Exception as exc:
Show Traceback
```

I think this is the timing issue or response issue. I am not sure because I am very new to python.

**Comment by dgunning** [comment]
Changed edgartools 2.32.0 to make Throttler a singleton. 
If there is still an issue with the code taking a long time, please open a new issue. For now closing this as an old issue
