### ISSUE TITLE
Filing 144

### ISSUE THREAD

**Issue by firmai** [dgunning/edgartools#8]
How much do you know about filings 144, for some reason AAPL only has two but maybe I am missing something. In anycase, here is some code that can help with parsing if you are looking into adding it: https://colab.research.google.com/drive/1VyH7hQ__W1Ab-HWRmPS2gywDHHZgsbrl?usp=sharing

**Comment by dgunning** [comment]
Thanks. Should be straightforward to add, especially with that sample code

**Comment by dgunning** [comment]
Implemented Form144 in version 1.15.5. 

Related blog post https://www.dgunning.com/research-insider-stock-sales/
