### ISSUE TITLE
Asyncio errors popping up

### ISSUE THREAD

**Issue by firmai** [dgunning/edgartools#81]
from calling the obj() 
filing.balance_sheet

---------------------------------------------------------------------------

RuntimeError                              Traceback (most recent call last)

[<ipython-input-11-2d616c4045e2>](https://localhost:8080/#) in <cell line: 1>()
----> 1 filing.balance_sheet

4 frames

[/usr/lib/python3.10/asyncio/runners.py](https://localhost:8080/#) in run(main, debug)
     31     """
     32     if events._get_running_loop() is not None:
---> 33         raise RuntimeError(
     34             "asyncio.run() cannot be called from a running event loop")
     35 

RuntimeError: asyncio.run() cannot be called from a running event loop

**Comment by dgunning** [comment]
What version of edgartools?

Are you running from a notebook?

**Comment by dgunning** [comment]
For now at the top of the colab do `pip install edgartools==2.27.5`

There was a breaking change introduced in 2.27.6 that fails only in a notebook. I am working on a fix for the notebook issue.

**Comment by dgunning** [comment]
Released 2.27.7 with a fix. Note that there is a change to the Financials so see if the new version works for you

**Comment by dgunning** [comment]
It's a pretty big change that I'm spending the next week or so documenting. On that note, in the process of documenting I found something broken so release 2.27.8

Try out this notebook

[Reading XBRL Data](https://github.com/dgunning/edgartools/blob/main/notebooks/Reading-Data-From-XBRL.ipynb)

**Comment by dgunning** [comment]
The call `filing.xbrl()` was still failing with async errors. This should be fixed now in 2.27.9

**Comment by dgunning** [comment]
Fixed in the latest version

**Comment by JackFan1002** [comment]
pip install nest_asyncio
import nest_asyncio
nest_asyncio.apply()
download_edgar_data()
