### ISSUE TITLE
Balance Sheet Values doesn't match

### ISSUE THREAD

**Issue by jmeireles1** [dgunning/edgartools#83]
Thank you for your effort and contribution to the repository.

I was testing the balance sheet and noticed a discrepancy: the values for Total Current Assets,Total Assets and Goodwill appear to be misaligned.

![image](https://github.com/user-attachments/assets/e30fd8a0-4cb5-4890-877c-632dbb2a0498)
![image2](https://github.com/user-attachments/assets/ee825fe7-790e-49ba-8406-0a15d46f1ea4)

`from edgar import *
from edgar.xbrl import *
import pandas as pd

filing: Filing = Company("PFE").get_filings(form="10-K").latest(1)

financials = filing.obj()

print(financials.balance_sheet)`

**Comment by dgunning** [comment]
I wrote a test and found a gap in the logic for picking up the values. I will take a look tomorrow

<img width="1137" alt="pfizer_current_assets" src="https://github.com/user-attachments/assets/9d61b482-864d-43fd-9d2a-c8cd1f0a6f96">

**Comment by dgunning** [comment]
Release 2.27.10

<img width="1329" alt="pfizer-balance-sheet" src="https://github.com/user-attachments/assets/d71c2e5a-b2af-4d64-a51e-4254fc26fee2">

**Comment by dgunning** [comment]
Closed as fixed
