### ISSUE TITLE
Cannot import XBRL

### ISSUE THREAD

**Issue by jdy214** [dgunning/edgartools#84]
Hello, I believe you may be aware but with the new update I am having an issue loading the edgar module.  Receiving import error: ImportError: cannot import name 'XBRL' from 'edgar.xbrl'.

I have uninstalled and reinstalled the module, but to no avail.

**Comment by dgunning** [comment]
What version of edgartools?

What is your import statement? `from edgar import *` ?

**Comment by jdy214** [comment]
Hi Dwight,

It is edgar 5.4.3
yes I am using the import statement from edgar import *

**Comment by jdy214** [comment]
ImportError                               Traceback (most recent call last)
Cell In[1], line 1
----> 1 from edgar import company
      2 set_identity('Justin Yaroni jdy214@stern.nyu.edu')

File ~\anaconda3\Lib\site-packages\edgar\__init__.py:6
      4 from .txtml import TXTML
      5 from .company import Company
----> 6 from .xbrl import XBRL, XBRLElement
      7 from .document import Document, Documents
      9 __version__ = "5.4.3"

ImportError: cannot import name 'XBRL' from 'edgar.xbrl' (C:\Users\xxx\anaconda3\Lib\site-packages\edgar\xbrl\__init__.py)

**Comment by jdy214** [comment]
ImportError                               Traceback (most recent call last)
Cell In[1], line 1
----> 1 from edgar import company
      2 set_identity('email')

File ~\anaconda3\Lib\site-packages\edgar\__init__.py:6
      4 from .txtml import TXTML
      5 from .company import Company
----> 6 from .xbrl import XBRL, XBRLElement
      7 from .document import Document, Documents
      9 __version__ = "5.4.3"

ImportError: cannot import name 'XBRL' from 'edgar.xbrl' (C:\Users\xxx\anaconda3\Lib\site-packages\edgar\xbrl\__init__.py)

**Comment by dgunning** [comment]
There is no Edgar 5.4.3.

```bash
pip uninstall edgar
pip install edgartools
```

**Comment by jdy214** [comment]
ImportError                               Traceback (most recent call last)
Cell In[2], line 1
----> 1 from edgar import *
      2 set_identity('log in credendtials')

File ~\anaconda3\Lib\site-packages\edgar\__init__.py:6
      4 from .txtml import TXTML
      5 from .company import Company
----> 6 from .xbrl import XBRL, XBRLElement
      7 from .document import Document, Documents
      9 __version__ = "5.4.3"

ImportError: cannot import name 'XBRL' from 'edgar.xbrl' (C:\Users\xxxx\anaconda3\Lib\site-packages\edgar\xbrl\__init__.py)

**Comment by jdy214** [comment]
that was embarassing I am able to import it now but am unable to use any classes, such as set_identity and Company

**Comment by jdy214** [comment]
that was embarrasing, thank you.

**Comment by jdy214** [comment]
This is an incredible improvement.  Thank you so much for your work on this.

**Comment by dgunning** [comment]
Closing
