### ISSUE TITLE
Accessing specific section of financial statement

### ISSUE THREAD

**Issue by Sindhuja217** [dgunning/edgartools#87]
Hi 

How to access the subheadings like operating activities, financing activities and investing activities in cash flow statement, not just that in the sameway I'm not able to access the subheadings like this in every financial statement, saying that when I'm converting them to dataframes it's hard to differentiate subheading and key features in the subheading

**Comment by dgunning** [comment]
Those subheadings should be in the dataframe returned from `cashflow.get_dataframe()`

If you need more metadata columns use `cashflow.get_dataframe(include_format=True)`

<img width="938" alt="cashflow" src="https://github.com/user-attachments/assets/f00cc186-d0c7-42c2-a37e-2c4f0a1ecf7a">


I don't know if this answers your question but I use those extra columns to distinguish rows.

I'm still improving the documentation so will add these

**Comment by Sindhuja217** [comment]
Thank you for your response That is really helpful, Is there any function that can extract just the companies revenue out of 10q forms and identify whether they are small medium or large scaled companies.

**Comment by dgunning** [comment]
You can get that a few ways
The coverpage displays some information about the company
<img width="667" alt="coverpage" src="https://github.com/user-attachments/assets/7fc827c5-0521-4458-b41d-1cd5941c62ac">

Converting to dataframe shows the concept and values
<img width="835" alt="coverpage_dataframe" src="https://github.com/user-attachments/assets/c333281e-5e0a-44e0-a29c-448c0e7702c8">

You can get the concept in code like so
`cover_page.get_concept("dei_EntityEmergingGrowthCompany")`

**Comment by Sindhuja217** [comment]
Thank you also I have been facing one more issue where I am not able to extract all the tables in a form q 10 
lets say Im executing a recent AAPL(Apple) form q10 
for few tables Im not able to get the exact tables using statements class
![Screenshot 2024-08-14 at 12 04 29 PM](https://github.com/user-attachments/assets/eb49c12c-a098-4170-944c-ea397eb1a515)
![Screenshot 2024-08-14 at 12 04 44 PM](https://github.com/user-attachments/assets/68fccf9b-e7b2-4986-b2b1-f6559713428b)
I am not getting the exact tables as shown in the documents

**Comment by dgunning** [comment]
That's on the roadmap. It's not hard to do, depends on how busy I am. (Pretty busy)

**Comment by Sindhuja217** [comment]
When will that be done ?

**Comment by Sindhuja217** [comment]
Can you please suggest how I can extract those tables those tables are very crucial for my dataset ?

**Comment by dgunning** [comment]
Very crucial .. well ok ..

Making this code generic will take some thinking but it is possible to get the value and convert to a pandas dataframe (or 2)

```python
from edgar import *
from edgar.financials import *
import pandas as pd
from rich import print
from io import StringIO

def get_financial_instrument_disclosure(financial_instruments):
    concept = financial_instruments.get_concept('us-gaap_FinancialInstrumentsDisclosureTextBlock')
    financial_instrument_disclosure = concept.value.get('Jun 29, 2024')
    return financial_instrument_disclosure

def get_financial_instrument_table(financial_instrument_disclosure):
    tables = pd.read_html(StringIO(financial_instrument_disclosure))
    return tables

company = Company("AAPL")
filings = company.get_filings(form="10-Q")
filing = filings[0]
xbrl_data = XBRLData.extract(filing)
statements = xbrl_data.statements
financial_instruments = statements['FinancialInstruments']
financial_instrument_disclosure = get_financial_instrument_disclosure(financial_instruments)
print(financial_instrument_disclosure)
tables = get_financial_instrument_table(financial_instrument_disclosure)
print(tables)

```

**Comment by Sindhuja217** [comment]
Thanks a lot that's really helpful,  I will check through it. Also I would be glad if you are going to implement that so that I can access these tables directly through statements as each formq 10 document has different tables and I need to extract all that data.

**Comment by dgunning** [comment]
You have a dataset where you need all the statements and tables from a 10-Q? or just specific ones

**Comment by Sindhuja217** [comment]
I plan to create a dataset by extracting all the tables from 10Q forms using Edgar tools, so right now am able to access only the few and not able to access the rest. So it will be helpful if I can extract them all.

Thanks,
Sindhu

**Comment by Sindhuja217** [comment]
Can you suggest me how can proceed further since my target is to create a dataset of form q10 that has all tables

**Comment by dgunning** [comment]
Apple's 10-Q has 78 statements/tables. You want all 78? What does your dataset look like?

**Comment by Sindhuja217** [comment]
Yes I want all 78 So Im planning to create a data where for one company I will create one excel and each sheet in my excel has information regarding one table 
[ACNB_CORP_Financial_Statements.xlsx](https://github.com/user-attachments/files/16627569/ACNB_CORP_Financial_Statements.xlsx)
I have attached on excel , for example in the same way I should be able to extract all other tables and add those tables in this excel, Please suggest me how can I proceed further

**Comment by dgunning** [comment]
Here is the bit of code to write to excel .. generated from ChatGPT. Add that to the code I shared earlier 
```python
import pandas as pd
from pandas import ExcelWriter

# Assuming you have a list of attachments with their dataframes
# Example structure:
# attachments = {
#     "attachment_1": [df1],  # Single dataframe
#     "attachment_2": [df2, df3],  # Multiple dataframes
#     ...
# }

def save_attachments_to_excel(attachments, output_file="output.xlsx"):
    with ExcelWriter(output_file, engine='openpyxl') as writer:
        for attachment_name, dfs in attachments.items():
            sheet_name = attachment_name[:31]  # Excel sheet names must be <= 31 chars
            if len(dfs) == 1:
                # Single dataframe, write directly to the sheet
                dfs[0].to_excel(writer, sheet_name=sheet_name, index=False)
            else:
                # Multiple dataframes, write each below the previous one
                start_row = 0
                for df in dfs:
                    df.to_excel(writer, sheet_name=sheet_name, startrow=start_row, index=False)
                    start_row += len(df) + 2  # Leave some space between tables

    print(f"Saved {len(attachments)} attachments to {output_file}")

# Example usage:
# attachments = {
#     "Attachment_1": [pd.DataFrame(...), pd.DataFrame(...)],
#     "Attachment_2": [pd.DataFrame(...)]
# }
# save_attachments_to_excel(attachments)

```

There's another bit of code I need to figure out - how to get the exact HTML tables from the statement

**Comment by Sindhuja217** [comment]
Kindly please let me know when you figure out how to get the exact html tables, Also I have one more doubt                               concept = financial_instruments.get_concept('us-gaap_FinancialInstrumentsDisclosureTextBlock') In this line from your previous code  from where did you find 'us-gaap_FinancialInstrumentsDisclosureTextBlock' so that I can change the same for other tables as well

**Comment by AlexanderGallus** [comment]
As you state this is urgent: 

Another way to do this, is to simply iterate through the filing.html() with BeautifulSoup (as it is installed as a dependency for this library anyways) and extract tables based on their respective HTML-tags.  

However, keep in mind that SEC-filings are semi-structured,  meaning that it is difficult to generalize code when trying to **properly** chunk filings or extract structures based on HTML. Tables, in particular, are often in unexpected formats and have extensive styling, making proper extraction of **only the semantic content without styling** - difficult. 

When executing the example code below, all tables are extracted with the last section before the table appended as a header. As styling is kept, you retain all of the tables' information.

The code:

```python
def get_html_tables_with_headers(html_string):
    soup = BeautifulSoup(html_string, 'html.parser')
    tables = soup.find_all('table')
    tables_with_headers = []
    for table in tables:
        previous_section = table.find_previous(string=True)
        header_text = previous_section.strip() if previous_section else ''
        table_html = f'<div>{header_text}</div>' + str(table)
        tables_with_headers.append(table_html)
    return tables_with_headers
```

The code with styling and empty cells removed to only retrieve the cells' values' would look like this:

```python
def get_html_tables_with_headers(html_string):
    soup = BeautifulSoup(html_string, 'html.parser')
    tables = soup.find_all('table')
    clean_tables = []
    for table in tables:
        previous_section = table.find_previous(string=True)
        table.attrs = {}
        for tag in table.find_all(True):
            tag.attrs = {}
        for cell in table.find_all(['td', 'th']):
            if not cell.get_text(strip=True):
                cell.decompose()
        for row in table.find_all('tr'):
            if not row.find_all(['td', 'th']):
                row.decompose()
        header_text = previous_section.strip() if previous_section else ''
        clean_table_html = f'<div>{header_text}</div>' + str(table)
        clean_tables.append(clean_table_html)
    return clean_tables
 ``` 
Due to the nature of tables in SEC-filings, however, it is unlikely that the table results with the latter approach are going to be in the intended format. Instead, table values are going to be shifted. You could however, pass the tables' contents to an LLM to regain the intended format.

**Comment by Sindhuja217** [comment]
Thank you so much, this code is working to extract all the tables.

**Comment by dgunning** [comment]
Closing as complete
