### ISSUE TITLE
Repeated Marketable Securities Values

### ISSUE THREAD

**Issue by EthanFulcher** [dgunning/edgartools#90]
Hello, I was using the edgartools to look at the balance sheet of AAPL in ending June 29, 2024 and found that the Marketable Securities in the Non-Current Assets section does not agree with the SEC filing Marketable Securities. After doing some further digging, I found the concept name for the Current Marketable Securities to be labeled "us-gaap_MarketableSecuritiesNoncurrent" and the Non-Current Marketable Securities to be labeled the same. So it appears that the values are duplicated, but interestingly the non-current marketable security duplicates the value of the current security. I have also checked the EDGAR naming of the source: https://www.sec.gov/ix?doc=/Archives/edgar/data/320193/000032019324000081/aapl-20240629.htm and it has them properly labeled. I am unsure how to go about resolving this issue.

**Comment by dgunning** [comment]
I will take a look

**Comment by dgunning** [comment]
Did the fix. Now testing. Will probably release today or tomorrow

**Comment by dgunning** [comment]
Released 2.27.13 with the fix. Please update and retest

pip install -U edgartools

**Comment by EthanFulcher** [comment]
This seems to have fixed the issue, thank you!
