### ISSUE TITLE
Keep on getting the same error (please help)

### ISSUE THREAD

**Issue by david08-08** [dgunning/edgartools#91]
Cell In[19], line 29
    revenue = income_statement_df.loc[income_statement_df['label'].str.contains('Revenue', case=False, na=False)].iloc[0, 1]

  File /opt/anaconda3/envs/nlp_env/lib/python3.11/site-packages/pandas/core/frame.py:4102 in __getitem__
    indexer = self.columns.get_loc(key)

  File /opt/anaconda3/envs/nlp_env/lib/python3.11/site-packages/pandas/core/indexes/base.py:3812 in get_loc
    raise KeyError(key) from err

KeyError: 'label'

**Comment by dgunning** [comment]
You can do this to get the values if you know the label or the concept name
```python
# By concept
balance_sheet.get_concept('us-gaap_AccountsReceivableNetCurrent').values
# By label
 balance_sheet.get_concept(label='Accounts receivable, net').values
```

**Comment by dgunning** [comment]
Closed as question answered
