### ISSUE TITLE
[Question] Error when trying to convert "income statement" object to a data frame

### ISSUE THREAD

**Issue by unparadise** [dgunning/edgartools#93]
Hello,

When I tried to convert the "income statement" object to a data frame using the following statement, I got an error message saying  "AttributeError: 'Statement' object has no attribute 'to_dataframe'. Did you mean: 'get_dataframe'?".

```
company = Company('AAPL')

# Get the 10 most recent 10-Ks
company_10Ks = company.get_filings(form="10-K").latest(10)

for i in range(0, len(company_10Ks)):
    dataframe_10Ks = company_10Ks[i].obj().income_statement.to_dataframe()
```

The code used to work. So, I was wondering whether the API has changed.

In addition, when I tried the sample code below. I received the same error message.
<img width="866" alt="image" src="https://github.com/user-attachments/assets/7057288d-ca2e-48fe-90e3-78d201ae572a">

<img width="593" alt="image" src="https://github.com/user-attachments/assets/3997b9da-c63b-4801-8100-b55743b815fe">

Thank you very much for your help!

**Comment by Ghedo44** [comment]
Hi,

It looks like the error occurs because you're calling `get_balance_sheet` and then trying to apply `.to_dataframe()` on it. However, since `get_balance_sheet` is a method, you should call it like this: `financials.get_balance_sheet()`.

If you want to access `balance_sheet` as an attribute. Here’s the corrected code:

`balance_sheet_df = financials.balance_sheet.to_dataframe()`

This should work because `balance_sheet` is likely an attribute that contains the data you want and has the `.to_dataframe()` method available.

Let me know if you need any further help!

**Comment by dgunning** [comment]
So the Financials are completely rewritten and it looks like in the rewrite the method was changed from `to_dataframe` to `get_dataframe`. I will look at changing the docs, or maybe alias the function. Let me think about it. 
At the very least I will change the documentation.

Can you use `get_dataframe`?

**Comment by unparadise** [comment]
Ghedo44 and dguning, thank you both for your help!

Combining the suggestions from both of you, I was able to fix the problem and make the code work. Pasted it below

```
from edgar import *

set_identity("unparadise unparadise@blahblah.com")

tenk = Company("AAPL").get_filings(form="10-K").latest(1).obj()
financials = tenk.financials

# using get_income_statement as a method
income_statement = financials.get_income_statement()

# convert to dataframe
income_statement_df = income_statement.get_dataframe()

print(income_statement_df)
```

@dgunning, would like to let you know that the following example in the document generates an error that says "AttributeError: 'Financials' object has no attribute 'balance_sheet'. Did you mean: 'get_balance_sheet'?

![image](https://github.com/user-attachments/assets/07f1b1a7-84c6-4a8c-b03d-3e3a80fdc24d)
