### ISSUE TITLE
.facts for XBRL instance is not working

### ISSUE THREAD

**Issue by MauritsBrinkman** [dgunning/edgartools#99]
Previously, as it is still mentioned in the documentation, we can obtain a dataframe with the facts (which includes the `namespace` and `DocumentFiscalYearFocus` in its columns) by 
```
filing_xbrl = filing.xbrl()
filing_xbrl.facts
```
In the '_filings.py' file, the `.xbrl()` method was recently changed, where now the output is of type `Optional[Union[XBRLData, XBRLInstance]]`, where previously this was `Optional[FilingXBRL]`, where this `FilingXBRL` class had a `.facts` attribute. Please, could we make `filing_xbrl.facts` working again? This issue is related to commit [`79e7daa0f2aabe77f06747331b6f127c3b761db4`](https://github.com/dgunning/edgartools/commits/a2969826ce10333131b4dad009b4936472053a31/edgar/_filings.py)

**Comment by dgunning** [comment]
Sorry about that ..the class was subject to a rewrite in order to add more functionality. Can you share how your code looked when you were using FilingXBRL.XBRLFacts .. there is likely a way to switch to the new way
